INSERT INTO indicadores (indicador_nombre, categoria, valor, unidad, periodo, region, desglose, fuente) VALUES
('Repitentes - Secundario', 'anuario_educacion', 1456, 'casos', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.9, '%', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 3142, 'casos', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 15, '%', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 919, 'casos', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 7.4, '%', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 2510, 'casos', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 20.3, '%', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 58, 'casos', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 12.3, '%', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 136, 'casos', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 28.9, '%', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 722, 'casos', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.9, '%', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1948, 'casos', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 18.5, '%', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 189, 'casos', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 9.2, '%', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 406, 'casos', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 19.8, '%', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 121, 'casos', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 10.2, '%', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 245, 'casos', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 20.7, '%', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 602, 'casos', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 5.9, '%', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1629, 'casos', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 15.9, '%', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 836, 'casos', 2024, 'Calamuchita', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 365, 'casos', 2024, 'Calamuchita', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 14597, 'casos', 2024, 'Capital', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 7031, 'casos', 2024, 'Capital', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 3030, 'casos', 2024, 'Colón', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1242, 'casos', 2024, 'Colón', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 963, 'casos', 2024, 'Cruz del Eje', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 388, 'casos', 2024, 'Cruz del Eje', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 452, 'casos', 2024, 'General Roca', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 209, 'casos', 2024, 'General Roca', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1669, 'casos', 2024, 'General San Martín', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 579, 'casos', 2024, 'General San Martín', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 399, 'casos', 2024, 'Ischilín', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 202, 'casos', 2024, 'Ischilín', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 824, 'casos', 2024, 'Juárez Celman', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 312, 'casos', 2024, 'Juárez Celman', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1262, 'casos', 2024, 'Marcos Juárez', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 486, 'casos', 2024, 'Marcos Juárez', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 120, 'casos', 2024, 'Minas', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 81, 'casos', 2024, 'Minas', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 88, 'casos', 2024, 'Pocho', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 47, 'casos', 2024, 'Pocho', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 515, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 229, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 2125, 'casos', 2024, 'Punilla', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 969, 'casos', 2024, 'Punilla', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 3036, 'casos', 2024, 'Río Cuarto', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1227, 'casos', 2024, 'Río Cuarto', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 761, 'casos', 2024, 'Río Primero', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 348, 'casos', 2024, 'Río Primero', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 212, 'casos', 2024, 'Río Seco', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 85, 'casos', 2024, 'Río Seco', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1594, 'casos', 2024, 'Río Segundo', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 595, 'casos', 2024, 'Río Segundo', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 618, 'casos', 2024, 'San Alberto', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 293, 'casos', 2024, 'San Alberto', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 886, 'casos', 2024, 'San Javier', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 333, 'casos', 2024, 'San Javier', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 2907, 'casos', 2024, 'San Justo', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1024, 'casos', 2024, 'San Justo', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1449, 'casos', 2024, 'Santa María', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 733, 'casos', 2024, 'Santa María', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 56, 'casos', 2024, 'Sobremonte', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 50, 'casos', 2024, 'Sobremonte', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1487, 'casos', 2024, 'Tercero Arriba', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 525, 'casos', 2024, 'Tercero Arriba', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 314, 'casos', 2024, 'Totoral', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 181, 'casos', 2024, 'Totoral', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 187, 'casos', 2024, 'Tulumba', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 105, 'casos', 2024, 'Tulumba', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1531, 'casos', 2024, 'Unión', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 576, 'casos', 2024, 'Unión', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico');