INSERT INTO indicadores (indicador_nombre, categoria, valor, unidad, periodo, region, desglose, fuente) VALUES
('Alumnos - Secundario', 'anuario_educacion', 134016, 'casos', 2024, 'Capital', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 21628, 'casos', 2024, 'Capital', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 142, 'casos', 2024, 'Capital', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 74313, 'casos', 2024, 'Capital', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 13666, 'casos', 2024, 'Capital', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 150, 'casos', 2024, 'Capital', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 59703, 'casos', 2024, 'Capital', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 7962, 'casos', 2024, 'Capital', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 58, 'casos', 2024, 'Colón', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 27502, 'casos', 2024, 'Colón', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 4272, 'casos', 2024, 'Colón', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 35, 'casos', 2024, 'Colón', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 17997, 'casos', 2024, 'Colón', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 2999, 'casos', 2024, 'Colón', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 23, 'casos', 2024, 'Colón', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 9505, 'casos', 2024, 'Colón', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1273, 'casos', 2024, 'Colón', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 20, 'casos', 2024, 'Cruz del Eje', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 6366, 'casos', 2024, 'Cruz del Eje', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1351, 'casos', 2024, 'Cruz del Eje', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 15, 'casos', 2024, 'Cruz del Eje', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 4526, 'casos', 2024, 'Cruz del Eje', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1043, 'casos', 2024, 'Cruz del Eje', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 5, 'casos', 2024, 'Cruz del Eje', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 1840, 'casos', 2024, 'Cruz del Eje', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 308, 'casos', 2024, 'Cruz del Eje', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 14, 'casos', 2024, 'General Roca', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 3128, 'casos', 2024, 'General Roca', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 661, 'casos', 2024, 'General Roca', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 9, 'casos', 2024, 'General Roca', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 2535, 'casos', 2024, 'General Roca', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 514, 'casos', 2024, 'General Roca', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 5, 'casos', 2024, 'General Roca', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 593, 'casos', 2024, 'General Roca', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 147, 'casos', 2024, 'General Roca', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 36, 'casos', 2024, 'General San Martín', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 13947, 'casos', 2024, 'General San Martín', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 2248, 'casos', 2024, 'General San Martín', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 19, 'casos', 2024, 'General San Martín', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 6726, 'casos', 2024, 'General San Martín', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1232, 'casos', 2024, 'General San Martín', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 17, 'casos', 2024, 'General San Martín', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 7221, 'casos', 2024, 'General San Martín', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1016, 'casos', 2024, 'General San Martín', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 7, 'casos', 2024, 'Ischilín', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 3752, 'casos', 2024, 'Ischilín', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 601, 'casos', 2024, 'Ischilín', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 5, 'casos', 2024, 'Ischilín', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 2910, 'casos', 2024, 'Ischilín', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 495, 'casos', 2024, 'Ischilín', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 2, 'casos', 2024, 'Ischilín', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 842, 'casos', 2024, 'Ischilín', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 106, 'casos', 2024, 'Ischilín', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 22, 'casos', 2024, 'Juárez Celman', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 6732, 'casos', 2024, 'Juárez Celman', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1136, 'casos', 2024, 'Juárez Celman', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 12, 'casos', 2024, 'Juárez Celman', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 3652, 'casos', 2024, 'Juárez Celman', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 665, 'casos', 2024, 'Juárez Celman', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 10, 'casos', 2024, 'Juárez Celman', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 3080, 'casos', 2024, 'Juárez Celman', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 471, 'casos', 2024, 'Juárez Celman', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 34, 'casos', 2024, 'Marcos Juárez', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 8763, 'casos', 2024, 'Marcos Juárez', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1748, 'casos', 2024, 'Marcos Juárez', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 16, 'casos', 2024, 'Marcos Juárez', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 4779, 'casos', 2024, 'Marcos Juárez', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 995, 'casos', 2024, 'Marcos Juárez', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 18, 'casos', 2024, 'Marcos Juárez', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 3984, 'casos', 2024, 'Marcos Juárez', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 753, 'casos', 2024, 'Marcos Juárez', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 2, 'casos', 2024, 'Minas', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 402, 'casos', 2024, 'Minas', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 201, 'casos', 2024, 'Minas', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 2, 'casos', 2024, 'Minas', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 402, 'casos', 2024, 'Minas', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 201, 'casos', 2024, 'Minas', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Minas', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Minas', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Minas', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 2, 'casos', 2024, 'Pocho', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 361, 'casos', 2024, 'Pocho', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 135, 'casos', 2024, 'Pocho', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 2, 'casos', 2024, 'Pocho', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 361, 'casos', 2024, 'Pocho', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 135, 'casos', 2024, 'Pocho', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Pocho', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Pocho', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Pocho', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 12, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 3446, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 744, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 9, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 2588, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 620, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 3, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 858, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 124, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 53, 'casos', 2024, 'Punilla', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 20306, 'casos', 2024, 'Punilla', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico');