INSERT INTO indicadores (indicador_nombre, categoria, valor, unidad, periodo, region, desglose, fuente) VALUES
('Personal docente - Primario', 'anuario_educacion', 1084, 'casos', 2024, 'Tercero Arriba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 58, 'casos', 2024, 'Tercero Arriba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 8686, 'casos', 2024, 'Tercero Arriba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 887, 'casos', 2024, 'Tercero Arriba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 10, 'casos', 2024, 'Tercero Arriba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 2357, 'casos', 2024, 'Tercero Arriba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 197, 'casos', 2024, 'Tercero Arriba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 33, 'casos', 2024, 'Totoral', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 2002, 'casos', 2024, 'Totoral', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 255, 'casos', 2024, 'Totoral', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 33, 'casos', 2024, 'Totoral', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 2002, 'casos', 2024, 'Totoral', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 255, 'casos', 2024, 'Totoral', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Totoral', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Totoral', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Totoral', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 41, 'casos', 2024, 'Tulumba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 1139, 'casos', 2024, 'Tulumba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 224, 'casos', 2024, 'Tulumba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 41, 'casos', 2024, 'Tulumba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 1139, 'casos', 2024, 'Tulumba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 224, 'casos', 2024, 'Tulumba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Tulumba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Tulumba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Tulumba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 98, 'casos', 2024, 'Unión', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 10213, 'casos', 2024, 'Unión', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 1081, 'casos', 2024, 'Unión', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 87, 'casos', 2024, 'Unión', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 7792, 'casos', 2024, 'Unión', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 909, 'casos', 2024, 'Unión', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 11, 'casos', 2024, 'Unión', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 2421, 'casos', 2024, 'Unión', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 172, 'casos', 2024, 'Unión', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 55, 'casos', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.8, '%', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 206, 'casos', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.9, '%', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 866, 'casos', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.6, '%', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 2330, 'casos', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.7, '%', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 292, 'casos', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 1, '%', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 727, 'casos', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.6, '%', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 62, 'casos', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 1, '%', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 137, 'casos', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.1, '%', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 0, 'casos', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0, '%', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 2, 'casos', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.1, '%', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 26, 'casos', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.2, '%', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 171, 'casos', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.1, '%', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 18, 'casos', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.5, '%', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 38, 'casos', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.1, '%', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 10, 'casos', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.2, '%', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 38, 'casos', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.6, '%', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 27, 'casos', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.3, '%', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 68, 'casos', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.7, '%', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 3, 'casos', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.8, '%', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 8, 'casos', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.1, '%', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 1, 'casos', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.3, '%', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 6, 'casos', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.6, '%', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0, '%', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 8, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.2, '%', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 161, 'casos', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.8, '%', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 323, 'casos', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.6, '%', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 9, 'casos', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0, '%', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 108, 'casos', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.4, '%', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 10, 'casos', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.2, '%', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 38, 'casos', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.7, '%', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 15, 'casos', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 1, '%', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 23, 'casos', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.5, '%', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 123, 'casos', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 1.1, '%', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico');