INSERT INTO indicadores (indicador_nombre, categoria, valor, unidad, periodo, region, desglose, fuente) VALUES
('Alumnos - Primario', 'anuario_educacion', 3514, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 341, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 31, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 3182, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 311, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 2, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 332, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 30, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 79, 'casos', 2024, 'Punilla', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 20389, 'casos', 2024, 'Punilla', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 1520, 'casos', 2024, 'Punilla', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 57, 'casos', 2024, 'Punilla', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 14551, 'casos', 2024, 'Punilla', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 1087, 'casos', 2024, 'Punilla', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 22, 'casos', 2024, 'Punilla', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 5838, 'casos', 2024, 'Punilla', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 433, 'casos', 2024, 'Punilla', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 155, 'casos', 2024, 'Río Cuarto', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 25965, 'casos', 2024, 'Río Cuarto', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 2176, 'casos', 2024, 'Río Cuarto', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 127, 'casos', 2024, 'Río Cuarto', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 18625, 'casos', 2024, 'Río Cuarto', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 1557, 'casos', 2024, 'Río Cuarto', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 28, 'casos', 2024, 'Río Cuarto', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 7340, 'casos', 2024, 'Río Cuarto', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 619, 'casos', 2024, 'Río Cuarto', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 73, 'casos', 2024, 'Río Primero', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 5445, 'casos', 2024, 'Río Primero', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 579, 'casos', 2024, 'Río Primero', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 69, 'casos', 2024, 'Río Primero', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 4543, 'casos', 2024, 'Río Primero', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 500, 'casos', 2024, 'Río Primero', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 4, 'casos', 2024, 'Río Primero', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 902, 'casos', 2024, 'Río Primero', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 79, 'casos', 2024, 'Río Primero', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 37, 'casos', 2024, 'Río Seco', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 1526, 'casos', 2024, 'Río Seco', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 229, 'casos', 2024, 'Río Seco', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 37, 'casos', 2024, 'Río Seco', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 1526, 'casos', 2024, 'Río Seco', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 229, 'casos', 2024, 'Río Seco', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Río Seco', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Río Seco', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Río Seco', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 73, 'casos', 2024, 'Río Segundo', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 10737, 'casos', 2024, 'Río Segundo', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 967, 'casos', 2024, 'Río Segundo', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 64, 'casos', 2024, 'Río Segundo', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 8860, 'casos', 2024, 'Río Segundo', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 835, 'casos', 2024, 'Río Segundo', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 9, 'casos', 2024, 'Río Segundo', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 1877, 'casos', 2024, 'Río Segundo', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 132, 'casos', 2024, 'Río Segundo', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 53, 'casos', 2024, 'San Alberto', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 4004, 'casos', 2024, 'San Alberto', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 428, 'casos', 2024, 'San Alberto', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 51, 'casos', 2024, 'San Alberto', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 3468, 'casos', 2024, 'San Alberto', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 393, 'casos', 2024, 'San Alberto', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 2, 'casos', 2024, 'San Alberto', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 536, 'casos', 2024, 'San Alberto', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 35, 'casos', 2024, 'San Alberto', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 52, 'casos', 2024, 'San Javier', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 6819, 'casos', 2024, 'San Javier', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 712, 'casos', 2024, 'San Javier', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 48, 'casos', 2024, 'San Javier', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 5695, 'casos', 2024, 'San Javier', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 620, 'casos', 2024, 'San Javier', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 4, 'casos', 2024, 'San Javier', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 1124, 'casos', 2024, 'San Javier', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 92, 'casos', 2024, 'San Javier', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 171, 'casos', 2024, 'San Justo', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 21495, 'casos', 2024, 'San Justo', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 2095, 'casos', 2024, 'San Justo', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 152, 'casos', 2024, 'San Justo', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 17348, 'casos', 2024, 'San Justo', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 1776, 'casos', 2024, 'San Justo', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 19, 'casos', 2024, 'San Justo', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 4147, 'casos', 2024, 'San Justo', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 319, 'casos', 2024, 'San Justo', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 67, 'casos', 2024, 'Santa María', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 12936, 'casos', 2024, 'Santa María', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 1048, 'casos', 2024, 'Santa María', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 56, 'casos', 2024, 'Santa María', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 9715, 'casos', 2024, 'Santa María', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 810, 'casos', 2024, 'Santa María', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 11, 'casos', 2024, 'Santa María', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 3221, 'casos', 2024, 'Santa María', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 238, 'casos', 2024, 'Santa María', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 12, 'casos', 2024, 'Sobremonte', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 384, 'casos', 2024, 'Sobremonte', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 60, 'casos', 2024, 'Sobremonte', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 12, 'casos', 2024, 'Sobremonte', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 384, 'casos', 2024, 'Sobremonte', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 60, 'casos', 2024, 'Sobremonte', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Sobremonte', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Sobremonte', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Sobremonte', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 68, 'casos', 2024, 'Tercero Arriba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 11043, 'casos', 2024, 'Tercero Arriba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico');