INSERT INTO indicadores (indicador_nombre, categoria, valor, unidad, periodo, region, desglose, fuente) VALUES
('Unidades educativas - Secundario', 'anuario_educacion', 8, 'casos', 2024, 'Totoral', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 1850, 'casos', 2024, 'Totoral', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 469, 'casos', 2024, 'Totoral', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 1, 'casos', 2024, 'Totoral', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 201, 'casos', 2024, 'Totoral', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 26, 'casos', 2024, 'Totoral', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 5, 'casos', 2024, 'Tulumba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 1182, 'casos', 2024, 'Tulumba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 292, 'casos', 2024, 'Tulumba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 5, 'casos', 2024, 'Tulumba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 1182, 'casos', 2024, 'Tulumba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 292, 'casos', 2024, 'Tulumba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Tulumba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Tulumba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Tulumba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 37, 'casos', 2024, 'Unión', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 10218, 'casos', 2024, 'Unión', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 2107, 'casos', 2024, 'Unión', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 18, 'casos', 2024, 'Unión', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 5804, 'casos', 2024, 'Unión', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1392, 'casos', 2024, 'Unión', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 19, 'casos', 2024, 'Unión', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 4414, 'casos', 2024, 'Unión', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 715, 'casos', 2024, 'Unión', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 566, 'casos', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 7.8, '%', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1420, 'casos', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 19.6, '%', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 8275, 'casos', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.2, '%', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 26529, 'casos', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 19.8, '%', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 1641, 'casos', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6, '%', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 4822, 'casos', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 17.5, '%', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 471, 'casos', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 7.4, '%', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1285, 'casos', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 20.2, '%', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 317, 'casos', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 10.1, '%', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 532, 'casos', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 17, '%', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 619, 'casos', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 4.4, '%', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1779, 'casos', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 12.8, '%', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 368, 'casos', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 9.8, '%', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 823, 'casos', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 21.9, '%', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 331, 'casos', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 4.9, '%', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1004, 'casos', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 14.9, '%', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 639, 'casos', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 7.3, '%', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1412, 'casos', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 16.1, '%', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 20, 'casos', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 5, '%', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 76, 'casos', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 18.9, '%', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 26, 'casos', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 7.2, '%', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 66, 'casos', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 18.3, '%', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 201, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 5.8, '%', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 525, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 15.2, '%', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 1288, 'casos', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.3, '%', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 3577, 'casos', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 17.6, '%', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 1590, 'casos', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.4, '%', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 4193, 'casos', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 17, '%', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 364, 'casos', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.4, '%', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 968, 'casos', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 17, '%', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 86, 'casos', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 5.7, '%', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 268, 'casos', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 17.8, '%', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 705, 'casos', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.7, '%', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1671, 'casos', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 15.8, '%', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 236, 'casos', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 5.8, '%', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 787, 'casos', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 19.5, '%', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 410, 'casos', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.5, '%', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1404, 'casos', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 22.1, '%', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico');