INSERT INTO indicadores (indicador_nombre, categoria, valor, unidad, periodo, region, desglose, fuente) VALUES
('Sobreedad - Primario', 'anuario_educacion', 375, 'casos', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 3.5, '%', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 24, 'casos', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.6, '%', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 56, 'casos', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.4, '%', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 35, 'casos', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.5, '%', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 162, 'casos', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.4, '%', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 41, 'casos', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.2, '%', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 143, 'casos', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.7, '%', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 125, 'casos', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 1, '%', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 269, 'casos', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.1, '%', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 1, 'casos', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.3, '%', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 1, 'casos', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.3, '%', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 57, 'casos', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.5, '%', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 155, 'casos', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.4, '%', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 12, 'casos', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.6, '%', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 42, 'casos', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.1, '%', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 1, 'casos', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.1, '%', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 1, 'casos', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.1, '%', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 82, 'casos', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.8, '%', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 292, 'casos', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.9, '%', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 539, 'casos', 2024, 'Calamuchita', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 88, 'casos', 2024, 'Calamuchita', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 10003, 'casos', 2024, 'Capital', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 1472, 'casos', 2024, 'Capital', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 1894, 'casos', 2024, 'Colón', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 255, 'casos', 2024, 'Colón', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 583, 'casos', 2024, 'Cruz del Eje', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 121, 'casos', 2024, 'Cruz del Eje', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 275, 'casos', 2024, 'General Roca', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 31, 'casos', 2024, 'General Roca', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 1127, 'casos', 2024, 'General San Martín', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 138, 'casos', 2024, 'General San Martín', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 353, 'casos', 2024, 'Ischilín', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 77, 'casos', 2024, 'Ischilín', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 486, 'casos', 2024, 'Juárez Celman', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 69, 'casos', 2024, 'Juárez Celman', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 836, 'casos', 2024, 'Marcos Juárez', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 72, 'casos', 2024, 'Marcos Juárez', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 82, 'casos', 2024, 'Minas', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 14, 'casos', 2024, 'Minas', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 56, 'casos', 2024, 'Pocho', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 50, 'casos', 2024, 'Pocho', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 305, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 36, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 1331, 'casos', 2024, 'Punilla', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 189, 'casos', 2024, 'Punilla', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 1924, 'casos', 2024, 'Río Cuarto', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 252, 'casos', 2024, 'Río Cuarto', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 493, 'casos', 2024, 'Río Primero', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 86, 'casos', 2024, 'Río Primero', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 174, 'casos', 2024, 'Río Seco', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 55, 'casos', 2024, 'Río Seco', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 836, 'casos', 2024, 'Río Segundo', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 131, 'casos', 2024, 'Río Segundo', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 345, 'casos', 2024, 'San Alberto', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 83, 'casos', 2024, 'San Alberto', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 602, 'casos', 2024, 'San Javier', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 110, 'casos', 2024, 'San Javier', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 1842, 'casos', 2024, 'San Justo', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 253, 'casos', 2024, 'San Justo', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 897, 'casos', 2024, 'Santa María', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 151, 'casos', 2024, 'Santa María', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 50, 'casos', 2024, 'Sobremonte', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 10, 'casos', 2024, 'Sobremonte', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 983, 'casos', 2024, 'Tercero Arriba', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 101, 'casos', 2024, 'Tercero Arriba', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 223, 'casos', 2024, 'Totoral', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 32, 'casos', 2024, 'Totoral', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 173, 'casos', 2024, 'Tulumba', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 51, 'casos', 2024, 'Tulumba', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 966, 'casos', 2024, 'Unión', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 115, 'casos', 2024, 'Unión', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 25, 'casos', 2024, 'Calamuchita', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 7259, 'casos', 2024, 'Calamuchita', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1201, 'casos', 2024, 'Calamuchita', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 15, 'casos', 2024, 'Calamuchita', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 4610, 'casos', 2024, 'Calamuchita', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 825, 'casos', 2024, 'Calamuchita', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 10, 'casos', 2024, 'Calamuchita', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 2649, 'casos', 2024, 'Calamuchita', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 376, 'casos', 2024, 'Calamuchita', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 292, 'casos', 2024, 'Capital', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico');