INSERT INTO indicadores (indicador_nombre, categoria, valor, unidad, periodo, region, desglose, fuente) VALUES
('Personal docente - Primario', 'anuario_educacion', 1084, 'casos', 2024, 'Tercero Arriba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 58, 'casos', 2024, 'Tercero Arriba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 8686, 'casos', 2024, 'Tercero Arriba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 887, 'casos', 2024, 'Tercero Arriba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 10, 'casos', 2024, 'Tercero Arriba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 2357, 'casos', 2024, 'Tercero Arriba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 197, 'casos', 2024, 'Tercero Arriba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 33, 'casos', 2024, 'Totoral', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 2002, 'casos', 2024, 'Totoral', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 255, 'casos', 2024, 'Totoral', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 33, 'casos', 2024, 'Totoral', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 2002, 'casos', 2024, 'Totoral', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 255, 'casos', 2024, 'Totoral', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Totoral', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Totoral', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Totoral', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 41, 'casos', 2024, 'Tulumba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 1139, 'casos', 2024, 'Tulumba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 224, 'casos', 2024, 'Tulumba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 41, 'casos', 2024, 'Tulumba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 1139, 'casos', 2024, 'Tulumba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 224, 'casos', 2024, 'Tulumba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Tulumba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Tulumba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Tulumba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 98, 'casos', 2024, 'Unión', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 10213, 'casos', 2024, 'Unión', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 1081, 'casos', 2024, 'Unión', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 87, 'casos', 2024, 'Unión', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 7792, 'casos', 2024, 'Unión', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 909, 'casos', 2024, 'Unión', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Primario', 'anuario_educacion', 11, 'casos', 2024, 'Unión', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Primario', 'anuario_educacion', 2421, 'casos', 2024, 'Unión', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Primario', 'anuario_educacion', 172, 'casos', 2024, 'Unión', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 55, 'casos', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.8, '%', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 206, 'casos', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.9, '%', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 866, 'casos', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.6, '%', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 2330, 'casos', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.7, '%', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 292, 'casos', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 1, '%', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 727, 'casos', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.6, '%', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 62, 'casos', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 1, '%', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 137, 'casos', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.1, '%', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 0, 'casos', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0, '%', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 2, 'casos', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.1, '%', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 26, 'casos', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.2, '%', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 171, 'casos', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.1, '%', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 18, 'casos', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.5, '%', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 38, 'casos', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.1, '%', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 10, 'casos', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.2, '%', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 38, 'casos', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.6, '%', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 27, 'casos', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.3, '%', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 68, 'casos', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.7, '%', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 3, 'casos', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.8, '%', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 8, 'casos', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.1, '%', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 1, 'casos', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.3, '%', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 6, 'casos', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.6, '%', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 0, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0, '%', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 8, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.2, '%', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 161, 'casos', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.8, '%', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 323, 'casos', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.6, '%', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 9, 'casos', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0, '%', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 108, 'casos', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.4, '%', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 10, 'casos', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.2, '%', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 38, 'casos', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.7, '%', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 15, 'casos', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 1, '%', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 23, 'casos', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.5, '%', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 123, 'casos', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 1.1, '%', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico');

INSERT INTO indicadores (indicador_nombre, categoria, valor, unidad, periodo, region, desglose, fuente) VALUES
('Sobreedad - Primario', 'anuario_educacion', 375, 'casos', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 3.5, '%', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 24, 'casos', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.6, '%', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 56, 'casos', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.4, '%', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 35, 'casos', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.5, '%', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 162, 'casos', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.4, '%', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 41, 'casos', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.2, '%', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 143, 'casos', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.7, '%', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 125, 'casos', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 1, '%', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 269, 'casos', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.1, '%', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 1, 'casos', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.3, '%', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 1, 'casos', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.3, '%', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 57, 'casos', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.5, '%', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 155, 'casos', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 1.4, '%', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 12, 'casos', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.6, '%', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 42, 'casos', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.1, '%', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 1, 'casos', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.1, '%', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 1, 'casos', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 0.1, '%', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Primario', 'anuario_educacion', 82, 'casos', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Primario', 'anuario_educacion', 0.8, '%', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Primario', 'anuario_educacion', 292, 'casos', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Primario', 'anuario_educacion', 2.9, '%', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 539, 'casos', 2024, 'Calamuchita', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 88, 'casos', 2024, 'Calamuchita', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 10003, 'casos', 2024, 'Capital', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 1472, 'casos', 2024, 'Capital', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 1894, 'casos', 2024, 'Colón', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 255, 'casos', 2024, 'Colón', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 583, 'casos', 2024, 'Cruz del Eje', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 121, 'casos', 2024, 'Cruz del Eje', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 275, 'casos', 2024, 'General Roca', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 31, 'casos', 2024, 'General Roca', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 1127, 'casos', 2024, 'General San Martín', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 138, 'casos', 2024, 'General San Martín', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 353, 'casos', 2024, 'Ischilín', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 77, 'casos', 2024, 'Ischilín', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 486, 'casos', 2024, 'Juárez Celman', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 69, 'casos', 2024, 'Juárez Celman', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 836, 'casos', 2024, 'Marcos Juárez', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 72, 'casos', 2024, 'Marcos Juárez', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 82, 'casos', 2024, 'Minas', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 14, 'casos', 2024, 'Minas', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 56, 'casos', 2024, 'Pocho', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 50, 'casos', 2024, 'Pocho', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 305, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 36, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 1331, 'casos', 2024, 'Punilla', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 189, 'casos', 2024, 'Punilla', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 1924, 'casos', 2024, 'Río Cuarto', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 252, 'casos', 2024, 'Río Cuarto', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 493, 'casos', 2024, 'Río Primero', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 86, 'casos', 2024, 'Río Primero', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 174, 'casos', 2024, 'Río Seco', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 55, 'casos', 2024, 'Río Seco', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 836, 'casos', 2024, 'Río Segundo', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 131, 'casos', 2024, 'Río Segundo', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 345, 'casos', 2024, 'San Alberto', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 83, 'casos', 2024, 'San Alberto', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 602, 'casos', 2024, 'San Javier', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 110, 'casos', 2024, 'San Javier', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 1842, 'casos', 2024, 'San Justo', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 253, 'casos', 2024, 'San Justo', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 897, 'casos', 2024, 'Santa María', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 151, 'casos', 2024, 'Santa María', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 50, 'casos', 2024, 'Sobremonte', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 10, 'casos', 2024, 'Sobremonte', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 983, 'casos', 2024, 'Tercero Arriba', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 101, 'casos', 2024, 'Tercero Arriba', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 223, 'casos', 2024, 'Totoral', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 32, 'casos', 2024, 'Totoral', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 173, 'casos', 2024, 'Tulumba', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 51, 'casos', 2024, 'Tulumba', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 966, 'casos', 2024, 'Unión', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Primario', 'anuario_educacion', 115, 'casos', 2024, 'Unión', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 25, 'casos', 2024, 'Calamuchita', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 7259, 'casos', 2024, 'Calamuchita', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1201, 'casos', 2024, 'Calamuchita', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 15, 'casos', 2024, 'Calamuchita', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 4610, 'casos', 2024, 'Calamuchita', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 825, 'casos', 2024, 'Calamuchita', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 10, 'casos', 2024, 'Calamuchita', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 2649, 'casos', 2024, 'Calamuchita', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 376, 'casos', 2024, 'Calamuchita', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 292, 'casos', 2024, 'Capital', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico');

INSERT INTO indicadores (indicador_nombre, categoria, valor, unidad, periodo, region, desglose, fuente) VALUES
('Alumnos - Secundario', 'anuario_educacion', 134016, 'casos', 2024, 'Capital', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 21628, 'casos', 2024, 'Capital', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 142, 'casos', 2024, 'Capital', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 74313, 'casos', 2024, 'Capital', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 13666, 'casos', 2024, 'Capital', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 150, 'casos', 2024, 'Capital', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 59703, 'casos', 2024, 'Capital', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 7962, 'casos', 2024, 'Capital', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 58, 'casos', 2024, 'Colón', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 27502, 'casos', 2024, 'Colón', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 4272, 'casos', 2024, 'Colón', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 35, 'casos', 2024, 'Colón', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 17997, 'casos', 2024, 'Colón', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 2999, 'casos', 2024, 'Colón', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 23, 'casos', 2024, 'Colón', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 9505, 'casos', 2024, 'Colón', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1273, 'casos', 2024, 'Colón', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 20, 'casos', 2024, 'Cruz del Eje', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 6366, 'casos', 2024, 'Cruz del Eje', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1351, 'casos', 2024, 'Cruz del Eje', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 15, 'casos', 2024, 'Cruz del Eje', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 4526, 'casos', 2024, 'Cruz del Eje', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1043, 'casos', 2024, 'Cruz del Eje', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 5, 'casos', 2024, 'Cruz del Eje', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 1840, 'casos', 2024, 'Cruz del Eje', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 308, 'casos', 2024, 'Cruz del Eje', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 14, 'casos', 2024, 'General Roca', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 3128, 'casos', 2024, 'General Roca', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 661, 'casos', 2024, 'General Roca', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 9, 'casos', 2024, 'General Roca', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 2535, 'casos', 2024, 'General Roca', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 514, 'casos', 2024, 'General Roca', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 5, 'casos', 2024, 'General Roca', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 593, 'casos', 2024, 'General Roca', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 147, 'casos', 2024, 'General Roca', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 36, 'casos', 2024, 'General San Martín', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 13947, 'casos', 2024, 'General San Martín', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 2248, 'casos', 2024, 'General San Martín', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 19, 'casos', 2024, 'General San Martín', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 6726, 'casos', 2024, 'General San Martín', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1232, 'casos', 2024, 'General San Martín', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 17, 'casos', 2024, 'General San Martín', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 7221, 'casos', 2024, 'General San Martín', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1016, 'casos', 2024, 'General San Martín', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 7, 'casos', 2024, 'Ischilín', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 3752, 'casos', 2024, 'Ischilín', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 601, 'casos', 2024, 'Ischilín', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 5, 'casos', 2024, 'Ischilín', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 2910, 'casos', 2024, 'Ischilín', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 495, 'casos', 2024, 'Ischilín', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 2, 'casos', 2024, 'Ischilín', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 842, 'casos', 2024, 'Ischilín', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 106, 'casos', 2024, 'Ischilín', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 22, 'casos', 2024, 'Juárez Celman', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 6732, 'casos', 2024, 'Juárez Celman', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1136, 'casos', 2024, 'Juárez Celman', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 12, 'casos', 2024, 'Juárez Celman', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 3652, 'casos', 2024, 'Juárez Celman', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 665, 'casos', 2024, 'Juárez Celman', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 10, 'casos', 2024, 'Juárez Celman', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 3080, 'casos', 2024, 'Juárez Celman', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 471, 'casos', 2024, 'Juárez Celman', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 34, 'casos', 2024, 'Marcos Juárez', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 8763, 'casos', 2024, 'Marcos Juárez', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1748, 'casos', 2024, 'Marcos Juárez', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 16, 'casos', 2024, 'Marcos Juárez', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 4779, 'casos', 2024, 'Marcos Juárez', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 995, 'casos', 2024, 'Marcos Juárez', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 18, 'casos', 2024, 'Marcos Juárez', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 3984, 'casos', 2024, 'Marcos Juárez', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 753, 'casos', 2024, 'Marcos Juárez', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 2, 'casos', 2024, 'Minas', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 402, 'casos', 2024, 'Minas', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 201, 'casos', 2024, 'Minas', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 2, 'casos', 2024, 'Minas', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 402, 'casos', 2024, 'Minas', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 201, 'casos', 2024, 'Minas', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Minas', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Minas', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Minas', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 2, 'casos', 2024, 'Pocho', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 361, 'casos', 2024, 'Pocho', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 135, 'casos', 2024, 'Pocho', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 2, 'casos', 2024, 'Pocho', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 361, 'casos', 2024, 'Pocho', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 135, 'casos', 2024, 'Pocho', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Pocho', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Pocho', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Pocho', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 12, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 3446, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 744, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 9, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 2588, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 620, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 3, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 858, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 124, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 53, 'casos', 2024, 'Punilla', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 20306, 'casos', 2024, 'Punilla', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico');

