INSERT INTO indicadores (indicador_nombre, categoria, valor, unidad, periodo, region, desglose, fuente) VALUES
('Personal docente - Secundario', 'anuario_educacion', 3094, 'casos', 2024, 'Punilla', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 27, 'casos', 2024, 'Punilla', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 12195, 'casos', 2024, 'Punilla', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1935, 'casos', 2024, 'Punilla', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 26, 'casos', 2024, 'Punilla', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 8111, 'casos', 2024, 'Punilla', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1159, 'casos', 2024, 'Punilla', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 75, 'casos', 2024, 'Río Cuarto', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 24736, 'casos', 2024, 'Río Cuarto', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 4263, 'casos', 2024, 'Río Cuarto', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 37, 'casos', 2024, 'Río Cuarto', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 14021, 'casos', 2024, 'Río Cuarto', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 2688, 'casos', 2024, 'Río Cuarto', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 38, 'casos', 2024, 'Río Cuarto', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 10715, 'casos', 2024, 'Río Cuarto', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1575, 'casos', 2024, 'Río Cuarto', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 16, 'casos', 2024, 'Río Primero', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 5690, 'casos', 2024, 'Río Primero', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1109, 'casos', 2024, 'Río Primero', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 10, 'casos', 2024, 'Río Primero', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 3939, 'casos', 2024, 'Río Primero', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 848, 'casos', 2024, 'Río Primero', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 6, 'casos', 2024, 'Río Primero', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 1751, 'casos', 2024, 'Río Primero', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 261, 'casos', 2024, 'Río Primero', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 5, 'casos', 2024, 'Río Seco', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 1503, 'casos', 2024, 'Río Seco', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 297, 'casos', 2024, 'Río Seco', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 5, 'casos', 2024, 'Río Seco', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 1503, 'casos', 2024, 'Río Seco', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 297, 'casos', 2024, 'Río Seco', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Río Seco', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Río Seco', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Río Seco', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 37, 'casos', 2024, 'Río Segundo', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 10570, 'casos', 2024, 'Río Segundo', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 2189, 'casos', 2024, 'Río Segundo', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 21, 'casos', 2024, 'Río Segundo', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 6254, 'casos', 2024, 'Río Segundo', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1525, 'casos', 2024, 'Río Segundo', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 16, 'casos', 2024, 'Río Segundo', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 4316, 'casos', 2024, 'Río Segundo', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 664, 'casos', 2024, 'Río Segundo', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 15, 'casos', 2024, 'San Alberto', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 4038, 'casos', 2024, 'San Alberto', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 911, 'casos', 2024, 'San Alberto', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 11, 'casos', 2024, 'San Alberto', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 3005, 'casos', 2024, 'San Alberto', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 740, 'casos', 2024, 'San Alberto', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 4, 'casos', 2024, 'San Alberto', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 1033, 'casos', 2024, 'San Alberto', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 171, 'casos', 2024, 'San Alberto', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 17, 'casos', 2024, 'San Javier', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 6340, 'casos', 2024, 'San Javier', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1219, 'casos', 2024, 'San Javier', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 11, 'casos', 2024, 'San Javier', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 4719, 'casos', 2024, 'San Javier', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 940, 'casos', 2024, 'San Javier', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 6, 'casos', 2024, 'San Javier', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 1621, 'casos', 2024, 'San Javier', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 279, 'casos', 2024, 'San Javier', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 66, 'casos', 2024, 'San Justo', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 21010, 'casos', 2024, 'San Justo', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 3931, 'casos', 2024, 'San Justo', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 36, 'casos', 2024, 'San Justo', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 13600, 'casos', 2024, 'San Justo', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 2800, 'casos', 2024, 'San Justo', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 30, 'casos', 2024, 'San Justo', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 7410, 'casos', 2024, 'San Justo', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1131, 'casos', 2024, 'San Justo', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 36, 'casos', 2024, 'Santa María', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 12392, 'casos', 2024, 'Santa María', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 2182, 'casos', 2024, 'Santa María', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 27, 'casos', 2024, 'Santa María', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 8795, 'casos', 2024, 'Santa María', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1707, 'casos', 2024, 'Santa María', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 9, 'casos', 2024, 'Santa María', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 3597, 'casos', 2024, 'Santa María', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 475, 'casos', 2024, 'Santa María', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 1, 'casos', 2024, 'Sobremonte', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 470, 'casos', 2024, 'Sobremonte', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 106, 'casos', 2024, 'Sobremonte', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 1, 'casos', 2024, 'Sobremonte', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 470, 'casos', 2024, 'Sobremonte', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 106, 'casos', 2024, 'Sobremonte', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Sobremonte', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Sobremonte', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Sobremonte', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 36, 'casos', 2024, 'Tercero Arriba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 10525, 'casos', 2024, 'Tercero Arriba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 2012, 'casos', 2024, 'Tercero Arriba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 19, 'casos', 2024, 'Tercero Arriba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 5867, 'casos', 2024, 'Tercero Arriba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1286, 'casos', 2024, 'Tercero Arriba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 17, 'casos', 2024, 'Tercero Arriba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 4658, 'casos', 2024, 'Tercero Arriba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 726, 'casos', 2024, 'Tercero Arriba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 9, 'casos', 2024, 'Totoral', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 2051, 'casos', 2024, 'Totoral', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 495, 'casos', 2024, 'Totoral', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico');

INSERT INTO indicadores (indicador_nombre, categoria, valor, unidad, periodo, region, desglose, fuente) VALUES
('Unidades educativas - Secundario', 'anuario_educacion', 8, 'casos', 2024, 'Totoral', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 1850, 'casos', 2024, 'Totoral', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 469, 'casos', 2024, 'Totoral', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 1, 'casos', 2024, 'Totoral', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 201, 'casos', 2024, 'Totoral', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 26, 'casos', 2024, 'Totoral', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 5, 'casos', 2024, 'Tulumba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 1182, 'casos', 2024, 'Tulumba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 292, 'casos', 2024, 'Tulumba', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 5, 'casos', 2024, 'Tulumba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 1182, 'casos', 2024, 'Tulumba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 292, 'casos', 2024, 'Tulumba', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Tulumba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Tulumba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 0, 'casos', 2024, 'Tulumba', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 37, 'casos', 2024, 'Unión', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 10218, 'casos', 2024, 'Unión', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 2107, 'casos', 2024, 'Unión', '{"sector": "Total"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 18, 'casos', 2024, 'Unión', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 5804, 'casos', 2024, 'Unión', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 1392, 'casos', 2024, 'Unión', '{"sector": "Estatal"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Unidades educativas - Secundario', 'anuario_educacion', 19, 'casos', 2024, 'Unión', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Alumnos - Secundario', 'anuario_educacion', 4414, 'casos', 2024, 'Unión', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Personal docente - Secundario', 'anuario_educacion', 715, 'casos', 2024, 'Unión', '{"sector": "Privado"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 566, 'casos', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 7.8, '%', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1420, 'casos', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 19.6, '%', 2024, 'Calamuchita', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 8275, 'casos', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.2, '%', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 26529, 'casos', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 19.8, '%', 2024, 'Capital', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 1641, 'casos', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6, '%', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 4822, 'casos', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 17.5, '%', 2024, 'Colón', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 471, 'casos', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 7.4, '%', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1285, 'casos', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 20.2, '%', 2024, 'Cruz del Eje', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 317, 'casos', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 10.1, '%', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 532, 'casos', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 17, '%', 2024, 'General Roca', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 619, 'casos', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 4.4, '%', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1779, 'casos', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 12.8, '%', 2024, 'General San Martín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 368, 'casos', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 9.8, '%', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 823, 'casos', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 21.9, '%', 2024, 'Ischilín', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 331, 'casos', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 4.9, '%', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1004, 'casos', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 14.9, '%', 2024, 'Juárez Celman', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 639, 'casos', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 7.3, '%', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1412, 'casos', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 16.1, '%', 2024, 'Marcos Juárez', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 20, 'casos', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 5, '%', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 76, 'casos', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 18.9, '%', 2024, 'Minas', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 26, 'casos', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 7.2, '%', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 66, 'casos', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 18.3, '%', 2024, 'Pocho', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 201, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 5.8, '%', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 525, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 15.2, '%', 2024, 'Presidente Roque Sáenz Peña', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 1288, 'casos', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.3, '%', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 3577, 'casos', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 17.6, '%', 2024, 'Punilla', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 1590, 'casos', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.4, '%', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 4193, 'casos', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 17, '%', 2024, 'Río Cuarto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 364, 'casos', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.4, '%', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 968, 'casos', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 17, '%', 2024, 'Río Primero', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 86, 'casos', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 5.7, '%', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 268, 'casos', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 17.8, '%', 2024, 'Río Seco', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 705, 'casos', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.7, '%', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1671, 'casos', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 15.8, '%', 2024, 'Río Segundo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 236, 'casos', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 5.8, '%', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 787, 'casos', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 19.5, '%', 2024, 'San Alberto', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 410, 'casos', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.5, '%', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1404, 'casos', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 22.1, '%', 2024, 'San Javier', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico');

INSERT INTO indicadores (indicador_nombre, categoria, valor, unidad, periodo, region, desglose, fuente) VALUES
('Repitentes - Secundario', 'anuario_educacion', 1456, 'casos', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.9, '%', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 3142, 'casos', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 15, '%', 2024, 'San Justo', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 919, 'casos', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 7.4, '%', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 2510, 'casos', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 20.3, '%', 2024, 'Santa María', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 58, 'casos', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 12.3, '%', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 136, 'casos', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 28.9, '%', 2024, 'Sobremonte', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 722, 'casos', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 6.9, '%', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1948, 'casos', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 18.5, '%', 2024, 'Tercero Arriba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 189, 'casos', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 9.2, '%', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 406, 'casos', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 19.8, '%', 2024, 'Totoral', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 121, 'casos', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 10.2, '%', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 245, 'casos', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 20.7, '%', 2024, 'Tulumba', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Repitentes - Secundario', 'anuario_educacion', 602, 'casos', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de repitencia - Secundario', 'anuario_educacion', 5.9, '%', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Sobreedad - Secundario', 'anuario_educacion', 1629, 'casos', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Tasa de sobreedad - Secundario', 'anuario_educacion', 15.9, '%', 2024, 'Unión', '{}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 836, 'casos', 2024, 'Calamuchita', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 365, 'casos', 2024, 'Calamuchita', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 14597, 'casos', 2024, 'Capital', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 7031, 'casos', 2024, 'Capital', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 3030, 'casos', 2024, 'Colón', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1242, 'casos', 2024, 'Colón', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 963, 'casos', 2024, 'Cruz del Eje', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 388, 'casos', 2024, 'Cruz del Eje', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 452, 'casos', 2024, 'General Roca', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 209, 'casos', 2024, 'General Roca', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1669, 'casos', 2024, 'General San Martín', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 579, 'casos', 2024, 'General San Martín', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 399, 'casos', 2024, 'Ischilín', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 202, 'casos', 2024, 'Ischilín', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 824, 'casos', 2024, 'Juárez Celman', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 312, 'casos', 2024, 'Juárez Celman', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1262, 'casos', 2024, 'Marcos Juárez', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 486, 'casos', 2024, 'Marcos Juárez', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 120, 'casos', 2024, 'Minas', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 81, 'casos', 2024, 'Minas', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 88, 'casos', 2024, 'Pocho', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 47, 'casos', 2024, 'Pocho', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 515, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 229, 'casos', 2024, 'Presidente Roque Sáenz Peña', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 2125, 'casos', 2024, 'Punilla', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 969, 'casos', 2024, 'Punilla', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 3036, 'casos', 2024, 'Río Cuarto', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1227, 'casos', 2024, 'Río Cuarto', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 761, 'casos', 2024, 'Río Primero', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 348, 'casos', 2024, 'Río Primero', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 212, 'casos', 2024, 'Río Seco', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 85, 'casos', 2024, 'Río Seco', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1594, 'casos', 2024, 'Río Segundo', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 595, 'casos', 2024, 'Río Segundo', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 618, 'casos', 2024, 'San Alberto', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 293, 'casos', 2024, 'San Alberto', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 886, 'casos', 2024, 'San Javier', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 333, 'casos', 2024, 'San Javier', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 2907, 'casos', 2024, 'San Justo', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1024, 'casos', 2024, 'San Justo', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1449, 'casos', 2024, 'Santa María', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 733, 'casos', 2024, 'Santa María', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 56, 'casos', 2024, 'Sobremonte', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 50, 'casos', 2024, 'Sobremonte', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1487, 'casos', 2024, 'Tercero Arriba', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 525, 'casos', 2024, 'Tercero Arriba', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 314, 'casos', 2024, 'Totoral', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 181, 'casos', 2024, 'Totoral', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 187, 'casos', 2024, 'Tulumba', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 105, 'casos', 2024, 'Tulumba', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 1531, 'casos', 2024, 'Unión', '{"genero": "Mujeres"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico'),
('Docentes - Secundario', 'anuario_educacion', 576, 'casos', 2024, 'Unión', '{"genero": "Varones"}'::jsonb, 'Ministerio de Educación - Anuario Estadístico');

