-- ============================================================
-- rbac_base_schema
--
-- Captures the RBAC base tables (roles, user_roles, role_permissions,
-- settings) into the repository. They were originally created from the
-- Supabase Studio dashboard and existed ONLY in the production database,
-- so the schema was unauditable and un-reproducible. This migration is
-- idempotent (IF NOT EXISTS / DROP POLICY IF EXISTS) and is the schema of
-- record going forward.
--
-- It ALSO fixes a latent instance of the RLS recursion bug that was fixed
-- for user_roles in 20260923140000_fix_rbac_policy_recursion.sql but never
-- applied to role_permissions: its "Escritura admin" policy is FOR ALL and
-- subqueries user_roles inline, so any authenticated write to
-- role_permissions could recurse. It is rewritten here to use the
-- SECURITY DEFINER is_admin() helper.
--
-- introspection source: live self-hosted production DB (2026-09-25).
-- Applies to: self-hosted production (supabase.ddna.com.ar).
-- ============================================================

-- ── roles ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.roles (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL UNIQUE,
  description text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ── user_roles ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_roles (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  role_id     integer NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
  assigned_by uuid REFERENCES auth.users(id),
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ── role_permissions ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.role_permissions (
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id  integer NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
  route    text NOT NULL,
  can_view boolean NOT NULL DEFAULT false,
  can_edit boolean NOT NULL DEFAULT false,
  UNIQUE (role_id, route)
);

-- ── settings ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.settings (
  key        text PRIMARY KEY,
  value      jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- ── is_admin() helper (idempotent; created in the prior migration) ──────
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles ur
    JOIN public.roles r ON r.id = ur.role_id
    WHERE ur.user_id = auth.uid() AND r.name = 'admin'
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_admin() TO anon, authenticated, service_role;

-- ── RLS enablement ──────────────────────────────────────────────────────
ALTER TABLE public.roles             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings          ENABLE ROW LEVEL SECURITY;

-- ── read policies (public SELECT, as in production) ─────────────────────
DROP POLICY IF EXISTS "Lectura pública de roles" ON public.roles;
CREATE POLICY "Lectura pública de roles" ON public.roles
  FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Lectura pública de user_roles" ON public.user_roles;
CREATE POLICY "Lectura pública de user_roles" ON public.user_roles
  FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Lectura pública de permisos" ON public.role_permissions;
CREATE POLICY "Lectura pública de permisos" ON public.role_permissions
  FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Allow public read access to settings" ON public.settings;
CREATE POLICY "Allow public read access to settings" ON public.settings
  FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Allow authenticated read access to settings" ON public.settings;
CREATE POLICY "Allow authenticated read access to settings" ON public.settings
  FOR SELECT TO public USING (true);

-- ── write policies: admin only, via is_admin() (no inline user_roles
--    subquery, so no recursion) ───────────────────────────────────────────
DROP POLICY IF EXISTS "Escritura admin roles" ON public.roles;
CREATE POLICY "Escritura admin roles" ON public.roles
  FOR ALL TO public USING (public.is_admin());

DROP POLICY IF EXISTS "Escritura admin user_roles" ON public.user_roles;
CREATE POLICY "Escritura admin user_roles" ON public.user_roles
  FOR ALL TO public USING (public.is_admin());

DROP POLICY IF EXISTS "Escritura admin role_permissions" ON public.role_permissions;
CREATE POLICY "Escritura admin role_permissions" ON public.role_permissions
  FOR ALL TO public USING (public.is_admin());
